### ISSUE TITLE
SHMIP tests failing

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#968]
Starting today, 2 of the SHMIP tests began failing in the nightly builds:

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=50583

The error looks like this: 

```
p=0: *** Caught standard std::exception of type 'std::logic_error' :

 Requirement( false ) FAILED
 Error occurred at: Albany/src/disc/stk/percept/stk_rebalance/GeomDecomp.cpp:143
 
 Error: Spatial Dimension not 1, 2, or 3, can not apply rotation.
```
@jewatkins I think this is due to the recent STK changes and your PR to fix the compilation errors that occurred.  Can you please have a look?

**Comment by jewatkins** [comment]
@bartgol might know more. He was the one who created the branch that fixed the builds after the stk changes.

**Comment by ikalash** [comment]
@jewatkins : Mauro said the same thing at the Albany meeting today.  Luca's in Italy, so we may have to wait for him to get back.

**Comment by ikalash** [comment]
@bartgol : do you know when you might have the chance to fix these tests?  Mauro mentioned that you are working part time while on travel, otherwise I would not bother you!

**Comment by bartgol** [comment]
I got back from Italy last night. I can take a look tomorrow (today is a bit hectic).

**Comment by ikalash** [comment]
Great, thanks @bartgol !

**Comment by bartgol** [comment]
I looked at the error, and reproduced it on mappy. However, I am at a loss as of what may be going wrong. The error is
```
Error: Spatial Dimension not 1, 2, or 3, can not apply rotation.
```
inside `apply_rotation` in GeomDecomp.cpp. However, when running in debug mode, it craps out at a different place, namely
```
     const unsigned ndim = stk::mesh::field_scalars_per_entity(nodal_coor,entity);
```
inside GeomDecomp.cpp, which is part of the stk_rebalance folder. This is inside a "callback" function, which Zoltan uses to do whatever stuff it does. I am not sure what is going on here, but I suppose the coord field is not what I would expect it to be? It's odd though, cause that stk call seems correct to me, unless the coord field was not yet set up when this fcn is called. That seems odd too, though with this fcn being a call back function, it's hard to tell, since I would have to know what zoltan is doing, and where it's grabbing stuff.

If anyone has any clue, I'm all ears. Meanwhile, I'll try to build trilinos in debug mode (sigh) and see if I get a bit more details from inside the `field_scalars_per_entity` call...

**Comment by ikalash** [comment]
Thanks, @bartgol , for looking into this.  Perhaps we should bring in a STK person.  @alanw0  do you have any thoughts on what could be causing this error, which started a few weeks ago?

**Comment by djglaze** [comment]
Hi @ikalash  and @bartgol ,

I dug around a bit in Percept to see what might be causing this error, and it looks like line 56 in `GeomDecomp.cpp` is coming back with a zero spatial dimension:
```
    const unsigned ndim = bulk_data.mesh_meta_data().spatial_dimension();
```
This can happen when you have an improperly-constructed `stk::mesh::MetaData` instance.  You can get into this state by either using a default-constructed `MetaData` (which starts with a spatial dimension of 0), or by using `stk::mesh::MeshBuilder` to build the `BulkData` and `MetaData` combo without first calling `set_spatial_dimension()`.

I haven't attempted to build Albany yet to trace through where the `MetaData` instance is coming from for these tests, but I suspect the answer is at the end of that trail.

**Comment by bartgol** [comment]
@djglaze that's a lot of info, thanks! At least now I know where to go look for any possible issue.

The test runs with 1 rank, so maybe something is going amiss after reading the mesh from file (it's a gmsh file). Perhaps I am not syncing the data, which causes all other ranks to have a MetaData with invalid data. I will dig a bit in that direction.

Thanks!

**Comment by alanw0** [comment]
@bartgol that sounds like an important clue. Can you point us to the place where the read-from-file happens? It is definitely required that the MetaData is identical on each MPI rank. stk-io is capable of reading the mesh in parallel, using either auto-decomp (meaning there is a single exodus file that hasn't been pre-decomposed), or in file-per-rank mode (meaning there is an exodus file for each MPI rank, with naming extensions `.<np>.<p>`).

**Comment by bartgol** [comment]
Thanks, I don't want to waste your time though. I take a first look at the code, since I wrote a good chunk of that reader. I may see the culprit relatively quickly, now that I know what I'm looking for. If I can't figure it out, I'll ping you again.

**Comment by mcarlson801** [comment]
Hi @alanw0, on a somewhat related note to this issue, it looks like there is a bug with STK's error handling. When this specific error is thrown, execution doesn't end and it gets stuck in an infinite loop. On all of our machines, when this test fails it keeps running until it hits the timeout time we have set. Is this bug something you are aware of?

This normally wouldn't be an issue except on one of the machines we test on (Perlmutter), this causes the node to get stuck in a busy state and all remaining tests end up timing out as well.

Anyway, it won't be a problem once we get this test fixed but I thought I'd point it out.

**Comment by alanw0** [comment]
@mcarlson801 Was there a resolution on @bartgol's investigation above, where the MetaData was possibly not identical across processors? If MetaData is becoming different on different MPI ranks, it has to be corrected in the calling code. I think we have debug-mode error checks for that, but they are expensive and not feasible to perform all the time.
In general there is a fundamental issue with detecting an error condition locally and how that should be handled. The best way to bring down the program gracefully is to allreduce the error condition and then every rank can do the same thing. But again that's expensive and so it's a difficult issue to address everywhere. 
But I'm happy to discuss further and evaluate whether there are better solutions.

**Comment by bartgol** [comment]
I dug a bit, and on my machine the meta data is well formed, with dimension 2 on all ranks. It is true that the error on CDash suggests a metaData of dimension 0, but on my machine it seems correct. It still fails, though, a bit later, at the line
```
const unsigned ndim = stk::mesh::field_scalars_per_entity(nodal_coor,entity);
```
with error message
```
 Requirement( f.entity_rank() == bulk.entity_rank(e) ) FAILED
 Error occurred at: develop-serial/include/stk_mesh/base/FieldBase.hpp:492
```
Indeed, printing the two ranks, I get that the field is defined at nodes, but the entity appears to be an element. I think the reason why [this](https://sems-cdash-son.sandia.gov/cdash/test/3650329) seems to be a different error is that it is a RELEASE build, and checks in Trilinos are disabled. The code goes a bit forward, but given the error, it fails to fill the coord array, leaving it of size 0. In fact, [the debug build](https://sems-cdash-son.sandia.gov/cdash/test/3651454) shows the same error I'm getting.

@mperego I can do plan B, and abandon the GMSH mesh in favor of using an exo file. However, I'm wondering if this is a signal of our rebalance code being broken. In particular, I wonder if this is the only test case where we do rebalance online. Perhaps something changed in Trilinos, some assumption in Zoltan maybe, and now we're setting up the rebalancing incorrectly.

**Comment by bartgol** [comment]
Ah, never mind. Looking at my mod, and seeing the error message above, I now realize what's happening. Basically, before my mods to adapt to stk changes, we were calling the stk method to get the vec dim only inside the if statement that checks that the entity is indeed a NODE. I moved this check outside the for look and the if statement, and put it [here](https://github.com/sandialabs/Albany/blob/5719078db9aa3c3dd22d0862212bc190b56daaf4/src/disc/stk/percept/stk_rebalance/GeomDecomp.cpp#L49), but that is incorrect, as the given entity is an element. Instead, I need to get the coordinates from the nodes of the element.

Anyhow, I will fix it in a second.
